const Disclaimer = () => {
  return (
    <div className="mx-auto flex max-w-[960px] flex-col items-center gap-12 px-4 pb-16 pt-8 mmd:gap-24 mmd:px-16 mmd:pb-32 mmd:pt-24">
      <div className="flex flex-col items-center justify-center gap-4">
        <h1 className="text-center text-4xl font-semibold md:text-5xl">
          RISK DISCLAIMER
        </h1>
        <div className="text-center text-xs text-themeLightGrey">
          Last Update: 30th September, 2024
        </div>
      </div>
      <div className="flex flex-col gap-4">
        <p>
        Please read this Risk Disclaimer carefully and fully before using our Artificial Intelligence (AI) Educational Bot and associated services (“AI Bot”) provided CG AI Network Pvt. Ltd. having its office address at 122, Vidyut Nagar C, Chitrakoot Marg, Vaishali Nagar, Jaipur, Rajasthan 302021 (“CG Network”) available at https://cgnet.ai/. By utilizing our AI Bot, you acknowledge and agree to the following:
        </p>
        <ul className="space-y-2">
          <li>
            1. 1.No Investment Advice: The information provided by the AI Bot does not constitute investment advice, financial advice, trading advice, or any other sort of advice. You should not treat any of the content available on our Platform as such. CG Network does not recommend that any token/digital asset should be bought, sold, or held by you. Conduct your due diligence and consult your financial advisor before making any investment decision.
          </li>
          <li>
            2. Educational Purpose Only: The output of the AI Bot provided by CG Network is for educational and illustrative purposes only. It does not imply a recommendation or solicitation to buy or sell any particular asset or to engage in any particular investment strategy. All investments involve risk, and losses may exceed the principal invested. All content, research, tools, and illustrations generated by the AI Bot are hypothetical in nature, based on AI recommendations that may be incomplete, inaccurate or lack context. CG Network does not guarantee the accuracy or completeness of the AI Bot&apos;s outputs. The AI Bot&apos;s output does not reflect actual investment results and does not account for real-world factors such as trading/ gas fees or other costs.
          </li>
          <li>
            3. Accuracy of Information: CG Network strives to ensure the accuracy of the AI Bot. However, CG Network is not responsible for any missing or incorrect information. You understand that you are using such information entirely AT YOUR OWN RISK.
          </li>
          <li>
            4. 4.Volatility and Market Risks: Token/digital asset markets are highly volatile, and prices can fluctuate significantly within short periods. The educational information provided by the AI Bot may not account for market conditions, sudden price movements, liquidity constraints, or regulatory changes.
          </li>
          <li>
            5. Inherent Risks: The AI Bot employs AI technology to provide educational content and trading insights based on predefined parameters and market conditions. While the AI bot aims to optimize educational strategies, it is important to understand that such information involves inherent risks. Unexpected market events, AI hallucinations, technical failures and algorithmic errors may occur, leading to unintended and inaccurate outputs.
          </li>
          <li>
            6. 6.Losses and Financial Obligations: The information provided by the AI Bot carries an inherent risk of financial loss. You should only invest in funds that you can afford to lose. You are responsible for monitoring your account balances, ensuring sufficient funds are available, and meeting any financial obligations resulting from trading activities, including transaction fees, margin requirements, and taxes.
          </li>
          <li>
            7. Limitation of Liability: CG Network, its affiliates, employees, vendors, consultants, representatives and agents shall not be responsible or  liable in any manner whatsoever for any losses, damages, costs, expenses, fees, including but not limited to direct, indirect, incidental, or consequential damages arising from the use of the AI Bot or any other services by CG Network.
          </li>
          <li>
            8. 8.No Guarantees of Profit: There is no guarantee of profit based on any outcome of the AI Bot. You should not rely on the AI Bot output as an indicator of future success.
          </li>
          <li>
            9. Individual Responsibility: You are solely responsible for making your own investment decisions, managing your trading accounts, and assuming the risks associated with trading activities. It is essential to conduct personal research, seek professional advice when necessary, and consider personal financial circumstances before engaging in any trading activities.
          </li>
          <li>
            10. 10.Third-Party Websites: CG Network is not responsible for the content of linked third-party websites. Third-party links and software applications may be used as part of the AI Bot output, these are used merely as a reference. CG Network cannot guarantee the accuracy of any such information.
          </li>
          <li>
            11. Warning: You should only trade or invest in a digital asset after you have thoroughly reviewed the relevant information of the token/digital asset and have read all terms and conditions carefully.
          </li>
        </ul>

        <p>
        By using CG Network’s AI Bot, you acknowledge that you have read, understood, and agreed to the terms of this Risk Disclaimer. You understand the risks associated with tokens/digital currency trading and accept full responsibility for your trading decisions and outcomes. This Risk Disclaimer must be read along with our Terms & Conditions, Privacy Policy, Cookie Policy and Trading Signal Disclaimers (collectively and individually, “Disclaimers”). These Disclaimers may be updated from time to time and it is upto you to check and familiarise yourself with the updated Disclaimers. 
        </p>
      </div>
    </div>
  )
}

export default Disclaimer
