const TermsAndConditions = () => {
  return (
    <div className="relative mx-auto flex max-w-[960px] flex-col items-center gap-12 px-4 pb-16 pt-8 mmd:gap-24 mmd:px-16 mmd:pb-32 mmd:pt-24">
      <div className="flex flex-col items-center justify-center gap-4">
        <h1 className="text-center text-4xl font-semibold md:text-5xl">
          TERMS OF USE
        </h1>
        <div className="text-center text-xs text-themeLightGrey">
          Last Update: 30/09/2024
        </div>
      </div>
      <div className="flex flex-col gap-4">
        <p>
          Please read these terms of use (“Terms”) carefully and fully before using our Artificial Intelligence Educational Bot (“AI Bot”) and associated Services offered by CG AI Network Pvt. Ltd. having its office address at 122, Vidyut Nagar C, Chitrakoot Marg, Vaishali Nagar, Jaipur, Rajasthan 302021 (“CG Network” or “we” or “us”).
        </p>
      </div>
      <div className="flex w-full flex-col gap-8">
        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">1. INTRODUCTION:</h3>
          <p>
            1.1. Service Overview: We offer educational content aimed at upskilling you in crypto trading, we enable this through an AI Bot and other tools including trading signals, recommendations and other services (“Services”). These Services are intended solely for informational and educational purposes and do not constitute financial, investment, legal, or any other form of professional advice and must not be construed as a solicitation or endorsement to buy, sell, or hold any cryptocurrency or digital assets.
          </p>
          <p>
            1.2. Acceptance of Terms: By accessing or using the Services, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree with any part of these Terms, please refrain from interacting with our AI Bot and availing our Services.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">2. ELIGIBILITY:</h3>
          <p>
            2.1. Age Requirement: You must be at least 18 years old to use this Service. If you are under 18 years old, we recommend that you use our services under the guidance and supervision of a parent or legal guardian. By allowing a minor to use our services, parents or legal guardians agree to these Terms on behalf of the minor and assume full responsibility for supervising their access and use of the platform.
          </p>
          <p>
            2.2. We encourage parents and guardians to discuss the potential risks associated with cryptocurrency trading and monitor the minor’s activities on the platform to ensure the content is appropriate for their age and understanding.
          </p>
          <p>
            2.3. Jurisdictional Restrictions: The Services are not intended for users in jurisdictions where our Services may be utilised for carrying out trading in cryptocurrency or other virtual assets, where such trading or holding such assets is prohibited by law. It is your responsibility to ensure that your use of the Services complies with all applicable laws.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">3. SERVICE DESCRIPTION:</h3>
          <p>
            3.1. Educational Purpose: The Services encompass educational resources, simulations, AI-driven content, trading signals and other tools for educating you about crypto trading. The Services do not execute trades or handle real financial transactions. All content generated by the Services, including trading signals, are hypothetical in nature and should be used for educational purposes only. Any risk associated with any trades undertaken as a result of the educational content is solely at your discretion.
          </p>
          <p>
            3.2. Parental Responsibility: Parents or guardians are encouraged to engage with the content to provide additional context and ensure that minors understand the risks associated with using the Services.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">4. ACCOUNT:</h3>
          <p>
            4.1. You may be required to register with us and create an account (“Account”) in order to access and use certain features of the Services. This may involve (without limitation):
          </p>
          <p>a. setting up a profile using a user ID and password;</p>
          <p>
            b. providing your name, email, contact number or linking a cryptocurrency wallet;
          </p>
          <p>c. receiving and entering one-time passwords; & </p>
          <p>
            d. providing any other data and information that we may require for providing our Services.
          </p>
          <p>
            4.2. In instances where you do not have a cryptocurrency wallet, we may create one for you.
          </p>
          <p>
            4.3. You must register using your true identity. Registration data and certain other information about you, including the information collected by us are governed by our Privacy Policy, accessible at https://cgnet.ai/help/privacy-policy.
          </p>
          <p>
            4.4. We reserve the right to refuse Service or terminate registered Accounts at our sole discretion.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">5. CONTENT:</h3>
          <p>
            5.1. Your Content: You may provide input to the AI Bot (“Input”), and receive output from the AI Bot based on the Input (“Output”). Such Input and Output are collectively referred to as content (“Content”). You are solely responsible for such Content, including ensuring that it does not violate any applicable law or these Terms. You represent and warrant that you have all rights, licenses, and permissions needed to provide Input to the AI Bot and avail our Services.
          </p>
          <p>
            5.2. Input: To the extent permitted by applicable law, you retain your ownership rights in the Input.
          </p>
          <p>
            5.3. Output: We hereby grant a limited, non-exclusive, non-transferable license to access and use the Output for personal, non-commercial purposes only. However, this assignment does not extend to any Output that may be similar or identical to that received by other users, given the inherent nature of the AI Bot.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">6. OUR USE OF CONTENT:</h3>
          <p>
            6.1. Service Improvement: We may use Content to provide, maintain, develop, and improve our Services, comply with applicable law or enforce these Terms.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">7. COMPLIANCE:</h3>
          <p>
            7.1. By accessing and using the AI Bot and associated Services you represent and warrant the following:
          </p>
          <ul className="flex list-inside flex-col gap-4">
            <li>a. You have not been sanctioned by your government;</li>
            <li>
              b. You are not on the Specially Designated Nationals (SDN) list maintained by the Office of Foreign Assets Control (OFAC) of the U.S. Department of the Treasury; and
            </li>
            <li>
              c. You are not located, incorporated, otherwise established in, a citizen of, or resident of, or have business operations in any country or region subject to a sanction regime (including sectoral sanctions) imposed by India, the EU, the UN, UK, USA. [e.g.: the Democratic People’s Republic of North Korea].
            </li>
          </ul>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">8. INTELLECTUAL PROPERTY:</h3>
          <p>
            8.1. Ownership: The AI Bot and associated Services including all algorithms, and intellectual property, are owned by us. You are granted a limited, non-exclusive, non-transferable license to access and use the AI Bot and associated Services for personal, non-commercial purposes only.
          </p>
          <p>
            8.2. User-Generated Content: All Content including Input, feedback and suggestions, may be used by us for improving the Service without any compensation to you.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">9. DISCLAIMER OF WARRANTIES:</h3>
          <p>
            9.1. No Warranty: The Service is provided &quot;as is&quot; without any warranties, express or implied, including but not limited to the accuracy, completeness, or reliability.
          </p>
          <p>
            9.2. No Financial Advice: The AI Bot and associated Services do not comprise, and must not be construed as financial, investment, legal, or tax advice. All information provided by the Services is for educational purposes only.
          </p>
          <p>
            9.3. Computer Virus: We are not liable for any harm that may be caused by the transmission of a computer virus, worm, time bomb, trojan horse, cancelbot, logic bomb or any other form of programming designed to damage, destroy or otherwise impair a computer&apos;s functionality or operation, including transmission, arising from you availing the Services.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">10. LIMITATION OF LIABILITY:</h3>
          <p>
            10.1. No Liability for Losses: You expressly understand and agree that neither we nor our affiliates will be liable for any indirect, incidental, special, consequential, exemplary damages, or damages for loss of profits including but not limited to, damages for loss of goodwill, data or other intangible losses (even if we have been advised of the possibility of such damages), whether based on contract, tort, negligence, strict liability or otherwise, resulting from:
          </p>
          <ul className="flex list-inside flex-col gap-4">
            <li>a. the use or the inability to use the Services;</li>
            <li>b. delays or disruptions in any of the Services;</li>
            <li>c. unauthorised access to or alteration of Content;</li>
            <li>
              d. viruses or other malicious software obtained by accessing our Services;
            </li>
            <li>
              e. any loss of cryptocurrency or digital assets due to information accessed as a result of the use of the Services;
            </li>
            <li>
              f. a suspension or other action taken with respect to your use of the Services; &
            </li>
            <li>g. any other matter relating to the Services. </li>
          </ul>
          <p>
            10.2. Force Majeure: We expressly disclaim liability for delays, failure in performance or interruption of the Services which result directly or indirectly from any cause or condition beyond our reasonable control, including any delay or failure due to any act of God, act of civil or military authorities, act of terrorists, civil disturbance, war, strike or other labour dispute, fire, interruption in telecommunications or internet services or network provider services, failure of equipment and/or software, other catastrophe or any other occurrence which is beyond our reasonable control.
          </p>
          <p>
            10.3. Inherent Risk: The information provided by the AI Bot, if used for investment purposes, carries an inherent risk of financial loss. You should only invest funds that you can afford to lose. You are responsible for monitoring your account balances, ensuring sufficient funds are available, and meeting any financial obligations resulting from trading activities, including transaction fees, margin requirements, and taxes. We undertake no liability with regard to any such activity undertaken by you.
          </p>
          <p>
            10.4. Limitation of Liability (regarding minors): We expressly disclaim liability for any financial decisions, trading activities, or other actions or decisions made by minors or by the minors parents or guardians on behalf of the minors based on information provided by the Services. We strongly recommend that minors do not engage in trading activities without parental guidance and proper financial education.+
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">11. GENERAL AND TRADING SIGNAL:</h3>
          <p>
            11.1. No Investment Advice: The information provided by the Services does not constitute investment, financial, trading, or any other form of professional advice. We do not recommend that any digital asset should be bought, sold, or held by you. You should conduct your due diligence and consult your financial advisor before making any investment decision.
          </p>
          <p>
            11.2. Educational Purpose Only: The Services are for educational and illustrative purposes only and must not be construed as a recommendation or solicitation to buy or sell any particular asset or engage in any particular investment strategy.
          </p>
          <p>
            11.3. Volatility and Market Risks: The information provided by the Services may not account for market conditions, sudden price movements, liquidity constraints, or regulatory changes. Cryptocurrency, token and digital asset markets are highly volatile, and prices can fluctuate significantly within short periods.
          </p>
          <p>
            11.4. Inherent Risks: The Services employ AI technology to provide educational content and trading insights. Unexpected market events, AI errors, technical failures, or algorithmic inaccuracies may occur, leading to unintended and inaccurate Output. 
          </p>
          <p>
            11.5. Losses and Financial Obligations: The information provided by the Service carries an inherent risk of financial loss. You should only invest funds that you can afford to lose and are solely responsible for monitoring account balances and meeting financial obligations.
          </p>
          <p>
            11.6. No Guarantees of Profit: There is no guarantee of profit based on any Output. You should not rely on any Output as an indicator of success.
          </p>
          <p>
            11.7. Regulatory Considerations: The Services including trading signals, have not been reviewed by any regulatory authority. You must consider the legal implications and risks associated with trading digital assets before undertaking any such trading activity.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">12. RESTRICTED ACTIVITIES:</h3>
          <p>
            12.1. In connection with your use of the Services or in the course of your interactions with the AI Chatbot you will not:
          </p>
          <ul className="flex list-inside flex-col gap-4">
            <li>
              a. Breach these Terms or our Disclaimers which may be accessed at https://cgnet.ai/.
            </li>
            <li>
              b. act in a manner that is defamatory, libellous, or threaten and/or harass our employees or any other user;
            </li>
            <li>
              c. provide false, inaccurate or misleading information while interacting with the AI Bot;
            </li>
            <li>
              d. violate any law, statute, ordinance, or regulation (particularly, those governing financial services, consumer protections, unfair competition, anti-discrimination or false advertising, as applicable in your jurisdiction);
            </li>
            <li>
              e. infringe our or any third party’s copyright, patent, trademark, trade secret or other intellectual property rights, or rights of publicity or privacy;
            </li>
            <li>
              f. input information that may be reasonably believed to be potentially fraudulent, misleading, or unlawful;
            </li>
            <li>
              g. engage in any fraudulent, deceptive, or illegal activity, including but not limited to providing false or misleading information, manipulating Content, or engaging in actions that are inconsistent with the intended educational purpose of the Services;
            </li>
            <li>
              h. refuse to cooperate in an investigation or provide confirmation of your identity or any information you provide to us, if requested to ensure compliance with these Terms;
            </li>
            <li>
              i. control an account that is linked to another account that has engaged in any restricted activity;
            </li>
            <li>
              j. circumvent any policies or determinations about your Account, such as temporary or indefinite suspensions or other Account holds, limitations, or restrictions, including but not limited to attempting to open new or additional accounts when an Account has been restricted, suspended, or otherwise limited; or using someone else’s account or abusing promotions which we may offer from time to time;
            </li>
            <li>
              k. take any action that imposes an unreasonable or disproportionately large load on our websites, software, or system (including any networks and servers used to provide any of the Services) operated by us or on our behalf;
            </li>
            <li>
              l. facilitate any virus, trojan horse, malware, worm, or other computer programming routine that attempts to or may damage, disrupt, corrupt, misuse, detrimentally interfere with, surreptitiously intercept, expropriate, or gain unauthorized access to any system, data, information, the AI Bot or our Services;
            </li>
            <li>
              m. use any robot, spider, manual process or any other automatic device to monitor, copy or modify our website;
            </li>
            <li>
              n. use any device, software, or routine to bypass our robot exclusion headers; 
            </li>
            <li>
              o. interfere or disrupt or attempt to interfere with or disrupt our websites, software, systems (including any networks and servers used to provide any of the Services) operated by us or on our behalf, any of the Services, or other users’ use of any of the Services;
            </li>
            <li>
              p. copy, reproduce, communicate to any third party, alter, modify, create derivative works, publicly display, or frame any Content without our or any applicable third party’s express written consent;
            </li>
            <li>
              q. give others access to your Account or use anyone else’s account; and
            </li>
            <li>
              r. manipulate Content or any other aspect of the Service in a way that could mislead users, create artificial Content, or otherwise undermine the educational purpose of the Service or the experience of any other user.
            </li>
          </ul>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">13. INVESTIGATION AND ACTION:</h3>
          <p>
            13.1. We have the right to investigate any violations of these Terms. Further, we reserve the right to cancel and/or suspend your Account or block access to the Services immediately and without notice if we determine, in our sole discretion, that your Account is associated with a restricted activity.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">
            14. CONSEQUENCES OF RESTRICTED ACTIVITIES:
          </h3>
          <p>
            14.1. If we believe that you’ve engaged in any restricted activity, we may take appropriate action at any time, in our sole discretion. These actions may include, but are not limited to:
          </p>
          <ul className="flex list-inside flex-col gap-4">
            <li>a. limit or suspend your Account;</li>
            <li>
              b. hold your Account or limit functionality if reasonably needed to protect against the risk of liability to us or a third party; &
            </li>
            <li>c. take legal action against you.</li>
          </ul>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">15. TERMINATION:</h3>
          <p>
            15.1. We may terminate or suspend access to the Service at any time, with or without notice, for any reason, including but not limited to violations of these Terms.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">
            16. GOVERNING LAW AND DISPUTE RESOLUTION:
          </h3>
          <p>
            16.1. If a dispute arises, our goal is to learn about and address your concerns. If we are unable to do so to your satisfaction, we aim to provide you with a neutral and cost-effective means of resolving the dispute quickly. You agree to notify us in writing of any dispute within thirty (30) days of when it arises. Disputes between you and us regarding the Services may be reported to customer service. 
          </p>
          <p>
            16.2. You acknowledge and agree that, in case of any dispute, controversy, divergence or claim that can&apos;t be solved by consultation or mediation, including any dispute in connection with the existence, validity, interpretation, performance, breach or termination of these Terms, we shall submit the dispute to the International Chamber of Commerce’s International Court of Arbitration. The seat and venue of the arbitration shall be Mumbai, India and apply to applicable laws determined under the ICC Rules of Arbitration. Only one arbitrator shall be appointed.
          </p>
          <p>
            16.3. The arbitration shall be conducted in English. The arbitral award shall be final and binding upon us. This Agreement will be governed by and interpreted in accordance with the English Common Law, without regard to conflict of law provisions.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">17. CONTACT:</h3>
          <p>
            17.1. For any grievances, please contact our Grievances Officer, Ishani Sharma at support@cryptograd.ai, or by phone at +91 92516 36327.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">18. AMENDMENTS:</h3>
          <p>
            18.1. Changes to Terms: We reserve the right to amend or update these Terms at any time. Your continued use of the Service after any change to these Terms shall constitute your consent to such changes.
          </p>
        </div>

        <div className="flex w-full flex-col gap-4">
          <h3 className="text-2xl">
            19. MISCELLANEOUS
          </h3>
          <p>
            19.1. Severability: If any provision of these Terms are found to be unenforceable or invalid, the remaining provisions shall remain in full force and effect.
          </p>
          <p>
            19.2. Entire Agreement: These Terms, the Disclaimers available at https://cgnet.ai/help/terms-and-conditions, https://cgnet.ai/help/risk-disclaimer, https://cgnet.ai/help/trading-signal-disclaimer and our Privacy Policy available at https://cgnet.ai/help/privacy-policy collectively constitute the entire agreement between you and us.
          </p>
        </div>
      </div>
    </div>
  )
}

export default TermsAndConditions
