export const TaskData = [
  {
    name: 'What is crypto, how to get started?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'What is Proof of Work (PoW)?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'Guide to setting up a crypto wallet',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'What is risk management?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'What is the ideal crypto portfolio allocation?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'Explain solidity and coding in blockchain',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'What is CBDC?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'How do I avoid scams and rugs?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'How do I find jobs in crypto?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'Which is the best CEX for trading?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'What is Bitcoin ETF?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'What is the Crypto Total MarketCap',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'Explain staking in detail',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'Write an erc20 smart contract',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'How can I use blockchain in supply chain?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'How to file Crypto Taxes?',
    icon: '',
    description: '',
    type: 'chat-genius',
  },
  {
    name: 'Analyze my trade',
    description: 'Share trade details',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'trade-analyzer',
  },
  {
    name: 'Why did this trade hit stop loss?',
    description: 'Share trade details',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'trade-analyzer',
  },
  {
    name: 'How to use order blocks to find entries?',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Analyse volume of this coin',
    description: 'Share ticker',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'trade-analyzer',
  },
  {
    name: 'Compare BTC & ETH',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Recommend optimal trade risk %',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Recommend hyped cryptocurrencies',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Analyse and look for liquidity levels for ETH',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Suggest a stop loss level for my trade',
    description: 'Share trade details',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'trade-analyzer',
  },
  {
    name: 'Optimize my trading strategy',
    description: 'Share your strategy',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'trade-analyzer',
  },
  {
    name: 'Share macro view on crypto',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Find support levels of BTC',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'How to manage risk on this trade?',
    description: 'Share Trade Details',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'trade-analyzer',
  },
  {
    name: 'Do a price action analysis on ETH',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Check current market sentiment',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Learn a new strategy',
    description: '',
    icon: '',
    type: 'trade-analyzer',
  },
  {
    name: 'Audit this smart contract',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Do a tax inspection of this contract',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Photo',
    type: 'contract-insight',
  },
  {
    name: 'Create a bubble map for this token',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Photo',
    type: 'contract-insight',
  },
  {
    name: 'Create a jeetmap for this coin',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Set alerts for burn events',
    icon: '',
    description: '',
    type: 'contract-insight',
  },
  {
    name: 'Find early buyers of this coin',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Top 10 holders for this smart contract',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Create a Whale Map for this token',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Team wallet analysis',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Alert on new liquidity pools with minimum 10 eth',
    icon: '',
    description: '',
    type: 'contract-insight',
  },
  {
    name: 'Social sentiment of this coin',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Track this wallet for all transactions',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Wallet Address',
    type: 'contract-insight',
  },
  {
    name: "Analyse this wallet's profitability",
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Alerts on newly deployed tokens with minimum 100 sniper wallets',
    icon: '',
    description: '',
    type: 'contract-insight',
  },
  {
    name: 'Alert & Track on calls by influencers for this coin',
    icon: '/CgAi/ChatAi/chartUp.png',
    description: 'Upload a Contract',
    type: 'contract-insight',
  },
  {
    name: 'Set alerts on fresh wallets aping a coin',
    icon: '',
    description: '',
    type: 'contract-insight',
  },
  {
    name: "Summarise today's crypto news",
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Share a list of upcoming ICOs',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Share latest airdrop farming opportunities',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Share a list of hyped fair launches',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Latest news on this coin',
    description: 'Share a ticker',
    icon: '/CgAi/ChatAi/chartUp.png',
    type: 'crypto-buzz',
  },
  {
    name: 'Major upcoming news events',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Top 5 influencer favourite coins for today',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: "Summarize this week's SEC crypto news",
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Top buzzed on-chain coin for today',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Summarize crypto influencers’ market insights from twitter',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'What is the latest news about NFT projects',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'What has Vitalik been up to recently',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'What are top VC firms investing in?',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Binance new listing posts',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Check current market sentiment for $SORA',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
  {
    name: 'Share latest news in Crypto AI developments',
    description: '',
    icon: '',
    type: 'crypto-buzz',
  },
]
